### ISSUE TITLE
No clear instructions 

### ISSUE THREAD

**Issue by ctr-alt-f3** [Spsden/Drip#6]
How to install it on any device? There aren't any clear instructions Is this project really dead?

**Comment by Bluscream** [comment]
I have recompiled the app and put a release on my fork: https://github.com/Bluscream/Drip/releases

**Comment by Spsden** [comment]
> How to install it on any device? There aren't any clear instructions Is this project really dead?

I really like working on the project but my college work eats up a lot of my time.
I have compiled an alpha version in the release section though.

**Comment by Spsden** [comment]
> I have recompiled the app and put a release on my fork: https://github.com/Bluscream/Drip/releases
